apiVersion: v1
kind: ConfigMap
metadata:
  name: adsoftsito-config
  labels:
    app: postgres
data:
  DEV_SECRET_KEY: i-love-adsoftsito-dev
  DEV_DATABASE: yvcfkhqm
  DEV_USER: yvcfkhqm
  DEV_PASSWORD: a0qkncXy9LrUeFVMDUg7L4-II6anlKUP
  DEV_HOST: jelani.db.elephantsql.com
  DEV_PORT: "5432"
