apiVersion: v1
kind: ConfigMap
metadata:
  name: adsoftsito-config
  labels:
    app: postgres
data:
  DEV_SECRET_KEY: i-love-adsoftsito-dev
  DEV_DATABASE: rqislgfe
  DEV_USER: rqislgfe
  DEV_PASSWORD: mRNXd5E166PhahSr2KlJkHpmunLs3zDo
  DEV_HOST: jelani.db.elephantsql.com
  DEV_PORT: "5432"
